"use client";

import { keepPreviousData, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Eye, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { PageHeading } from "@/components/page-heading";
import { Pagination } from "@/components/pagination";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { createVip, deleteUser, getUsers, toggleUserBlock, updateVerification, type VipPayload } from "@/lib/api";
import type { User } from "@/lib/types";
import { cn, errorMessage, initials } from "@/lib/utils";

const tabs = [{ key: "all", label: "All Users" }, { key: "client", label: "Client" }, { key: "tradesman", label: "Tradesman" }, { key: "vip", label: "VIP" }];
const skills = ["Phone Tech", "Computer Tech", "Plumber", "Electrician", "Carpenter", "Joinery", "Mobile Mech", "Painter", "Appliance", "AC Tech", "Tile Man", "Mason", "Glass Man", "Roofer", "Welder/Gate", "Pool Cleaner", "Tree Cutter", "Landscaper", "Auto Body", "Contractor", "Maid Service", "Caterer"];

function nameOf(user: User) { return user.name || `${user.firstName || ""} ${user.lastName || ""}`.trim() || "Unnamed member"; }

function VipDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const client = useQueryClient();
  const mutation = useMutation({ mutationFn: createVip, onSuccess: (r) => { toast.success(r.message); client.invalidateQueries({ queryKey: ["users"] }); onOpenChange(false); }, onError: (e) => toast.error(errorMessage(e)) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); mutation.mutate(Object.fromEntries(f) as unknown as VipPayload); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogTitle>Add VIP Member</DialogTitle><form onSubmit={submit} className="mt-7 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="First Name"><Input name="firstName" required /></Field><Field label="Last Name"><Input name="lastName" required /></Field><Field label="Email"><Input name="email" type="email" required /></Field><Field label="Phone Number"><Input name="phoneNumber" required /></Field><Field label="Home Area"><Input name="homeArea" required placeholder="San Fernando" /></Field><Field label="Main Skill"><select name="mainSkill" required className="form-control"><option value="">Select a skill</option>{skills.map((skill) => <option key={skill}>{skill}</option>)}</select></Field></div><Field label="Travel Range"><div className="grid gap-2">{["5km - Local only", "Trinidad wide", "T&T wide"].map((range) => <label key={range} className="flex cursor-pointer items-center justify-between rounded-md border border-black/20 px-4 py-3 text-sm has-[:checked]:border-brand has-[:checked]:bg-brand-soft"><span>{range}</span><input type="radio" name="travelRange" value={range} required className="size-4 accent-brand" /></label>)}</div></Field><Field label="Pitch 0/140"><textarea name="pitch" maxLength={140} required className="form-control min-h-24 resize-none" placeholder="A short introduction" /></Field><Field label="Typical Rate"><div className="grid grid-cols-[1fr_1fr] gap-2"><Input name="rateAmount" type="number" min="0" required placeholder="TT$ amount" /><select name="rateUnit" className="form-control"><option>Per day</option><option>Per hour</option><option>Per job</option></select></div></Field><div className="flex gap-3 pt-2"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending ? "Creating..." : "Create New Member"}</Button></div></form></DialogContent></Dialog>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium"><span className="mb-2 block">{label}</span>{children}</label>; }

export default function UsersPage() {
  const client = useQueryClient(); const [type, setType] = useState("all"); const [page, setPage] = useState(1); const [vipOpen, setVipOpen] = useState(false); const [selected, setSelected] = useState<User | null>(null); const limit = 8;
  const query = useQuery({ queryKey: ["users", type, page], queryFn: () => getUsers({ type, page, limit }), placeholderData: keepPreviousData });
  const refresh = () => client.invalidateQueries({ queryKey: ["users"] });
  const block = useMutation({ mutationFn: toggleUserBlock, onSuccess: (r) => { toast.success(r.message); refresh(); }, onError: (e) => toast.error(errorMessage(e)) });
  const remove = useMutation({ mutationFn: deleteUser, onSuccess: (r) => { toast.success(r.message); refresh(); }, onError: (e) => toast.error(errorMessage(e)) });
  const verify = useMutation({ mutationFn: ({ id }: { id: string }) => updateVerification(id, "verified"), onSuccess: (r) => { toast.success(r.message); refresh(); }, onError: (e) => toast.error(errorMessage(e)) });
  function actions(user: User) { return <div className="flex items-center justify-end gap-2"><button title={user.isBlocked ? "Activate user" : "Block user"} aria-label={user.isBlocked ? "Activate user" : "Block user"} className={cn("text-green-600", user.isBlocked && "text-amber-600")} onClick={() => block.mutate(user._id)}><ShieldCheck size={17} /></button>{user.tradesmanProfile?.verificationStatus === "pending" && <button title="Verify tradesman" aria-label="Verify tradesman" className="text-green-600" onClick={() => verify.mutate({ id: user.tradesmanProfile!._id })}><CheckCircle2 size={17} /></button>}<button title="View member" aria-label="View member" className="text-blue-500" onClick={() => setSelected(user)}><Eye size={17} /></button><button title="Delete member" aria-label="Delete member" className="text-red-500" onClick={() => { if (confirm(`Delete ${nameOf(user)}?`)) remove.mutate(user._id); }}><Trash2 size={17} /></button></div>; }
  return <><PageHeading title="User list" /><div className="mb-4 flex flex-wrap items-center gap-2">{tabs.map((tab) => <button key={tab.key} onClick={() => { setType(tab.key); setPage(1); }} className={cn("h-10 rounded-full border border-black/10 bg-white px-4 text-sm shadow-sm", type === tab.key && "border-brand bg-brand text-white")}>{tab.label}</button>)}{type === "vip" && <Button size="sm" className="ml-auto" onClick={() => setVipOpen(true)}><Plus size={16} />Add Vip Member</Button>}</div>
    <section className="overflow-hidden rounded-lg border border-black/5 bg-white shadow-sm">
      {query.isLoading ? <div className="space-y-2 p-4">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-16" />)}</div> : <>
        <div className="hidden md:block"><table className="w-full table-fixed"><thead className="bg-brand-soft text-left"><tr><th className="w-[46%] px-7 py-4">MEMBER</th><th className="w-[28%] px-4 py-4 text-center">TYPE</th><th className="px-7 py-4 text-right">ACTIONS</th></tr></thead><tbody>{query.data?.users.map((user) => <tr key={user._id} className="border-b border-black/5"><td className="px-5 py-[18px]"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#f0f1f4] text-xs font-bold">{initials(nameOf(user)).slice(0, 1)}</span><div className="min-w-0"><div className="truncate text-sm font-bold">{nameOf(user)}</div><div className="truncate text-sm text-[#a0a7b4]">{user.email}</div></div></div></td><td className="px-4 py-3 text-center"><div className="text-sm font-bold capitalize">{user.role}</div>{user.tradesmanProfile?.mainSkill && <div className="text-[11px] text-muted">{user.tradesmanProfile.mainSkill}</div>}</td><td className="px-7 py-3">{actions(user)}</td></tr>)}</tbody></table></div>
        <div className="divide-y divide-black/5 md:hidden">{query.data?.users.map((user) => <article key={user._id} className="p-4"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#f0f1f4] text-xs font-bold">{initials(nameOf(user)).slice(0, 1)}</span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-bold">{nameOf(user)}</h3><p className="truncate text-xs text-muted">{user.email}</p><p className="mt-1 text-xs capitalize">{user.role}</p></div>{actions(user)}</div></article>)}</div>
        {!query.data?.users.length && <p className="p-12 text-center text-sm text-muted">No members found.</p>}<Pagination page={query.data?.meta.page || 1} totalPages={query.data?.meta.totalPages || 1} total={query.data?.meta.total || 0} pageSize={limit} onPage={setPage} />
      </>}
    </section><VipDialog open={vipOpen} onOpenChange={setVipOpen} />
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-w-lg"><DialogTitle>Member details</DialogTitle>{selected && <div className="mt-6 space-y-4"><div className="flex items-center gap-4 rounded-md border border-[#d9e8f2] p-4"><span className="grid size-14 place-items-center rounded-full bg-accent text-xl font-bold">{initials(nameOf(selected))}</span><div><h3 className="font-bold">{nameOf(selected)}</h3><p className="text-sm capitalize text-muted">{selected.role}</p></div></div><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted">Email</dt><dd className="font-medium">{selected.email}</dd></div><div><dt className="text-muted">Phone</dt><dd className="font-medium">{selected.phoneNumber || "Not provided"}</dd></div><div><dt className="text-muted">Area</dt><dd className="font-medium">{selected.area || selected.tradesmanProfile?.homeArea || "Not provided"}</dd></div><div><dt className="text-muted">Status</dt><dd className="font-medium">{selected.isBlocked ? "Blocked" : "Active"}</dd></div></dl></div>}</DialogContent></Dialog>
  </>;
}
